### ISSUE TITLE
Suggestion: use xfwm4-theme-generator for automatically deriving the correct XFWM4 theme

### ISSUE THREAD

**Issue by manticore-projects** [Fausto-Korpsvart/Tokyonight-GTK-Theme#58]
https://github.com/andreldm/xfwm4-theme-generator

Works like a charm for this theme, absolute match.

**Comment by Fausto-Korpsvart** [comment]
> https://github.com/andreldm/xfwm4-theme-generator
> 
> Works like a charm for this theme, absolute match.

Thanks for the suggestion, @manticore-projects, I will check and see how it works, and then work on it.
