### ISSUE TITLE
Firefox buttons are huge?

### ISSUE THREAD

**Issue by mrjones2014** [Fausto-Korpsvart/Tokyonight-GTK-Theme#62]
Hey, I'm using this theme on NixOS and with the latest version, my firefox buttons look like this?

![image](https://github.com/user-attachments/assets/134ae019-2043-4b4a-ad75-8989749a018b)

**Comment by mrjones2014** [comment]
Firefox seems to be the only application with this issue.

**Comment by mrjones2014** [comment]
normal buttons for comparison

![image](https://github.com/user-attachments/assets/c7663960-1a70-4914-bbd1-4da8454e6b07)

**Comment by Fausto-Korpsvart** [comment]
> Hey, I'm using this theme on NixOS and with the latest version, my firefox buttons look like this?
> 
> ![image](https://private-user-images.githubusercontent.com/8648891/351904082-134ae019-2043-4b4a-ad75-8989749a018b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTU3NzgsIm5iZiI6MTcyMTkxNTQ3OCwicGF0aCI6Ii84NjQ4ODkxLzM1MTkwNDA4Mi0xMzRhZTAxOS0yMDQzLTRiNGEtYWQ3NS04OTg5NzQ5YTAxOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTM1MTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFiYWNjOTRlNWZjN2RiMzlhOGQzNzg4YTc4YTc1MjQ5Mzc5ODhkNjQ4MDVhZDEwNjQzYTI4M2MxMTc2ZmEwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-IMvOs09P2LhiZLbmOxJnPDaboVH7JnZY2_oVoyM0wk)

It is possible that the NIXOS package is not up to date, I have already fixed this problem, try installing from this repository and let me know if you still have the problem.
I would also like, if possible, that you share the NIXOS link to check if it is up to date.

Firefox with the latest theme update.
![ff](https://github.com/user-attachments/assets/7abf726b-7999-4e3a-b357-bd29061077d5)

**Comment by mrjones2014** [comment]
Ah yeah, looks like the Nixpkgs package is currently pinned to `e9790345a6231cd6001f1356d578883fac52233a`: https://github.com/NixOS/nixpkgs/blob/d0907b75146a0ccc1ec0d6c3db287ec287588ef6/pkgs/data/themes/tokyonight-gtk-theme/generic.nix#L20

Looks like we just need to update the Nixpkgs package, thanks!
