### ISSUE TITLE
Broken Nicotine+

### ISSUE THREAD

**Issue by andro404-MC** [Fausto-Korpsvart/Tokyonight-GTK-Theme#64]
Without the theme
![Screenshot_2024-08-11-22-02-15](https://github.com/user-attachments/assets/e5d80132-10ba-4757-ac0d-93dac243a008)

With the theme
![Screenshot_2024-08-11-21-58-42](https://github.com/user-attachments/assets/b1e8a509-4288-47d4-aa00-ff7fc01b3d44)

**Comment by Fausto-Korpsvart** [comment]
It's already fixed, you can try it and let me know if you find more errors.
Again, thanks for reporting.

**Comment by andro404-MC** [comment]
Thanks.
Sorry for responding sooooo late I tried compiling the theme, but I didn't have time to figure it out I finally updated today, and it's fantastic, a lot of other improvements.

Thanks for the great work ✨
