### ISSUE TITLE
Theme Parser expects Number

### ISSUE THREAD

**Issue by RayJW** [Fausto-Korpsvart/Tokyonight-GTK-Theme#66]
I'm not sure if this started with GNOME 47, but I saw that the `gnome-control-c` process regularly logs the following errors:

> gnome-control-c[121694]: Theme parser error: gtk.css:7955:18-22: Expected a number
> gnome-control-c[121694]: Theme parser error: gtk.css:7967:18-22: Expected a number
> gnome-control-c[121694]: Theme parser error: gtk-dark.css:7955:18-22: Expected a number
> gnome-control-c[121694]: Theme parser error: gtk-dark.css:7967:18-22: Expected a number

I checked and these are the lines causing problems: `border-radius: none;` so it seems like none is not a valid value here.

**Comment by Fausto-Korpsvart** [comment]
> I'm not sure if this started with GNOME 47, but I saw that the `gnome-control-c` process regularly logs the following errors:
> 
> > gnome-control-c[121694]: Theme parser error: gtk.css:7955:18-22: Expected a number
> > gnome-control-c[121694]: Theme parser error: gtk.css:7967:18-22: Expected a number
> > gnome-control-c[121694]: Theme parser error: gtk-dark.css:7955:18-22: Expected a number
> > gnome-control-c[121694]: Theme parser error: gtk-dark.css:7967:18-22: Expected a number
> 
> I checked and these are the lines causing problems: `border-radius: none;` so it seems like none is not a valid value here.

Thanks for the tip, I will fix and update soon.

**Comment by RayJW** [comment]
I think you might have forgotten to apply the fix before publishing the new update. I'm still getting the error + a new issue since updating to the newest commit.

```shell
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
```

**Comment by Fausto-Korpsvart** [comment]
> I think you might have forgotten to apply the fix before publishing the new update. I'm still getting the error + a new issue since updating to the newest commit.
> 
> ```shell
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
> Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
> ```

Actually that's already fixed, I just forgot to add it in this update, I'll update it soon, as I'm fixing some small bugs in Gnome Shell and then I'll do the update, thanks for the reminder.

**Comment by RayJW** [comment]
> > I think you might have forgotten to apply the fix before publishing the new update. I'm still getting the error + a new issue since updating to the newest commit.
> > ```shell
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:4883:3-8: No property named "borde"
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7977:18-22: Expected a number
> > Oct 31 16:45:10 host gnome-control-c[73010]: Theme parser error: gtk.css:7990:18-22: Expected a number
> > ```
> 
> Actually that's already fixed, I just forgot to add it in this update, I'll update it soon, as I'm fixing some small bugs in Gnome Shell and then I'll do the update, thanks for the reminder.

Oh alright, no problem then! I'll leave #70 open for now, in case you want to merge the other fix. Otherwise, feel free to close it at any time :)
